{% set name = "seawater_crm" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seawater_crm-{{ version }}.tar.gz
  sha256: af6e76a580f3bd7d275b72b83b0f1069a440d8c15a8b1eac26a081882b66b970

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas

test:
  imports:
    - seawater_crm
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Certified values for seawater reference materials
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/seawater_crm

extra:
  recipe-maintainers:
    - mvdh7
